favicon: /img/tu.png

custom_css: /css/custom.css

navbar:
  blog_title: Runner8
  
index:
  slogan:
    enable: true
    text: 欢 迎 来 到 Runner8 的 Blog!
    
footer:
  content: '
    <a href="https://github.com/Runner-8" target="_blank" rel="nofollow noopener"><span>GitHub</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  '
  
post:
  toc:
    placement: left
  update_date:
    enable: true
    
about:
  name: "Runner8"
  intro: "A student of IoT Engineering!"
  icons:
    - { class: "iconfont icon-telegram-fill", link: "https://t.me/Runner8_GL", tip: "Telegram" }
    - { class: "iconfont icon-google-fill", link: "https://google.com" }
    - { class: "iconfont icon-qq-fill", qrcode: "/img/qq.png" }